T = int(input())


for t in range(1,1+T):
    n = list(map(str, input().split()))
    input_list = list(map(str, input().split()))
    n0 = input_list.count('ZRO')
    n1 = input_list.count('ONE')
    n2 = input_list.count('TWO')
    n3 = input_list.count('THR')
    n4 = input_list.count('FOR')
    n5 = input_list.count('FIV')
    n6 = input_list.count('SIX')
    n7 = input_list.count('SVN')
    n8 = input_list.count('EGT')
    n9 = input_list.count('NIN')
    result = []
    result.append('ZRO '*n0)
    result.append('ONE '*n1)
    result.append('TWO '*n2)
    result.append('THR '*n3)
    result.append('FOR '*n4)
    result.append('FIV '*n5)
    result.append('SIX '*n6)
    result.append('SVN '*n7)
    result.append('EGT '*n8)
    result.append('NIN '*n9)
    print(f'#{t}')
    print(*result)
